require 'bundler/setup'

require 'tty-prompt'
require 'pastel'
require_relative 'core/mastermind'
require_relative 'players/human'
require_relative 'players/computer'
require_relative 'gameloop'

prompt = TTY::Prompt.new
pastel = Pastel.new

Display.print_help

first_run = true

loop do
  puts
  puts "Let's play #{pastel.bold('Mastermind')}#{first_run ? '' : ' again'}!"
  puts

  choice = prompt.enum_select('What would you like to do?') do |menu|
    menu.choice 'Break a code generated by the computer', :break
    menu.choice 'Make a code and let the computer try and guess it', :make
    menu.choice 'Read game rules', :help unless first_run
    menu.choice 'Exit game', :exit
  end

  case choice
  when :break
    player = Human.new
  when :make
    player = Computer.new
    secret = Human.new.next_guess(nil) # a bit of a hack
  when :help
    Display.print_help
    puts
    prompt.keypress('Press any key to continue...')
    next # restart loop
  when :exit
    sure = prompt.yes?('Are you sure you want to exit?', default: false)
    exit if sure
    next # go to begining of loop if not sure
  end

  # run a game 
  Gameloop.new(Mastermind.new(secret), player).run

  first_run = false
end
